# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
production:
  adapter: mysql2
  database: mycrm_production
  host: localhost
  username: root
  pool: 5
  password: Ezbc83651$
  encoding: utf8

development:
  adapter: mysql2
  database: mycrm_development
  host: localhost
  username: root
  pool: 5
  password: Ezbc83651$
  encoding: utf8

test:
  adapter: mysql2
  database: mycrm_test
  host: localhost
  username: root
  pool: 5
  password: Ezbc83651$
  encoding: utf8